Study/mintblue
weekly-academy/kotlin-springboot-101 pull request #12
Opened 2022-02-19 10:51 UTC by mint-blue

워들 모듈을 만들었습니다.

2022-02-19 14:01 UTC, heli-os requested changes

2022-02-19 14:01 UTC, heli-os commented on wordle/README.md
> +* 워들단어 그대로 비교해서 매칭하면 [g,g,g,g,g]로 리턴 (green)
구현을 어떻게 할지가 아니라, 무엇을 구현할지에 초점을 맞춰서 작성해보면 더 좋을 것 같아요. 구현을 마무리 한 뒤 테스트를 한다고 했을 때 어떤 테스트를 해야 할것인지 생각해보면 도움이 될 것 같습니다.

2022-02-19 14:01 UTC, heli-os commented on wordle/README.md
> +6X5의 버튼을 만듬
개발을 전혀 모르는 사람도 이해할 수 있게끔 일반적인 용어/표현으로 작성하는게 좋을 것 같습니다. (가능한 구체적으로)

예) 첫 번째 글자가 정답과 일치할 경우 첫 번째 블럭은 녹색으로 표시한다
예) 두 번째 글자가 정답에 포함되어 있지만 위치가 다르면 두 번쨰 블럭은 노란색으로 표시한다

2022-02-21 09:58 UTC, mint-blue commented on wordle/README.md
> +* 워들단어 그대로 비교해서 매칭하면 [g,g,g,g,g]로 리턴 (green)
다른분들의 readme를 읽어보니 제가 요구사항정의나 기능정의가 아닌 글코딩을 했네요. 
피드백 감사합니다!

2022-02-23 16:43 UTC, heli-os approved these changes

2022-02-23 16:43 UTC, merged