2022년 02월 23일 과제 제출 (minhee0327)
weekly-academy/kotlin-springboot-101 pull request #14
Opened 2022-02-20 12:58 UTC by minhee0327

안녕하세요 2022년 02월 23일(수) 과제 제출합니다 :D

2022-02-20 15:54 UTC, heli-os requested changes

2022-02-20 15:54 UTC, heli-os commented on wordle/README.md
> +- 모듈 생성을 했는데 지난번에 생성한 모듈의 build.gradle 파일과 비교해보니 plugin 과 dependency가 다르게 생겨서 build.gradle 파일에 대해서 좀 더 알아보려고 합니다..!
저번에 만들어진 파일을 보시면 `build.gradle.kts` 라는 파일명을 갖고 있는데요. 모듈을 만들 때 Gradle -> Kotlin/JVM 까지 선택한 뒤 위쪽에 있는 `Kotlin DSL Build Script` 라는 걸 체크하고 모듈을 만드시면 될거에요 ㅎㅎ

2022-02-20 15:54 UTC, heli-os commented on wordle/README.md
> +  - 입력받은 글자를 하나씩 확인하면서 철자와, 위치가 일치하면 녹색(GREEN), 정답 단어에는 있는 철자이나 위치는 일치 하지 않았다면 노랑색(YELLOW),둘 다 아닌 경우 회색(GRAY)로 5크기의 배열에 담는다.
해당 조건을 조금 더 자세하게 풀어보면 좋을 것 같아요.

2022-02-21 00:10 UTC, minhee0327 commented on wordle/README.md
> +- 모듈 생성을 했는데 지난번에 생성한 모듈의 build.gradle 파일과 비교해보니 plugin 과 dependency가 다르게 생겨서 build.gradle 파일에 대해서 좀 더 알아보려고 합니다..!
오...ㅎㅎ 알려주신 덕분에 빨리 찾아서 이해할 수 있었습니다 감사합니다 ㅎㅎ
https://www.charlezz.com/?p=45140

2022-02-23 00:09 UTC, minhee0327 commented on wordle/README.md
> +  - 입력받은 글자를 하나씩 확인하면서 철자와, 위치가 일치하면 녹색(GREEN), 정답 단어에는 있는 철자이나 위치는 일치 하지 않았다면 노랑색(YELLOW),둘 다 아닌 경우 회색(GRAY)로 5크기의 배열에 담는다.
해당조건을 읽기 쉽게만 풀어두었습니다..!ㅎㅎ 오늘 스터디에서 뵙겠습니다 :D
(자세히는 조금 더 고민해봐야할 것 같습니다.!)

2022-02-23 16:44 UTC, heli-os approved these changes

2022-02-23 16:44 UTC, merged