wordle 기능 정리_20220223
weekly-academy/kotlin-springboot-101 pull request #16
Opened 2022-02-21 08:24 UTC by LeeJeongGi

2022-02-21 09:18 UTC, heli-os commented on wordle/README.md
> +* 입력한 문자와 정답 문자가 위치,값 모두 다를 경우 회색 표시
실제 유즈 케이스를 바탕으로 조금 더 자세하게 작성해보면 좋을 것 같아요.

2022-02-21 09:19 UTC, heli-os requested changes

2022-02-21 09:19 UTC, heli-os commented on wordle/README.md
> +* 입력한 문자와 정답 문자가 위치,값 모두 다를 경우 회색 표시
실제 유즈 케이스를 바탕으로 조금 더 자세하게 작성해보면 좋을 것 같아요.

2022-02-22 05:56 UTC, LeeJeongGi commented on wordle/README.md
> +* 입력한 문자와 정답 문자가 위치,값 모두 다를 경우 회색 표시
게임 진행 상황을 좀 더 자세하게 작성해 보았습니다~!

2022-02-22 08:24 UTC, heli-os requested changes

2022-02-22 08:24 UTC, heli-os commented on wordle/README.md
> +  * 정답 문자에 없는 경우 회색
조금 더 구체적으로 작성해볼 수 있지 않을까요? 예외 케이스를 최대한 많이 작성해보면 좋을 것 같아요.

ex)
apple <-> april
hills <-> kills

2022-02-23 16:45 UTC, heli-os approved these changes

2022-02-23 16:45 UTC, merged