wordle 요구사항 정리
weekly-academy/kotlin-springboot-101 pull request #17
Opened 2022-02-21 11:26 UTC by JPWon-1

요구사항 정리하였습니다.
주요기능과 예외처리를 적었습니다.

2022-02-22 08:26 UTC, heli-os requested changes

2022-02-22 08:26 UTC, heli-os commented on wordle/README.md
> +  - 다른 자리에 맞는 단어를 입력했을 경우 해당 칸은 노랑색으로 변경
apple <-> april
같은 경우는 p가 위치가 맞는 것도 있고, 아닌 것도 존재해요. 또 a는 위치까지 맞고, l은 위치가 다르구요. 이런건 어떻게 풀어볼 수 있을까요?

2022-02-23 03:59 UTC, JPWon-1 commented on wordle/README.md
> +  - 다른 자리에 맞는 단어를 입력했을 경우 해당 칸은 노랑색으로 변경
> apple <-> april 같은 경우는 p가 위치가 맞는 것도 있고, 아닌 것도 존재해요. 또 a는 위치까지 맞고, l은 위치가 다르구요. 이런건 어떻게 풀어볼 수 있을까요?

우선적으로 같은 자리에 같은 알파벳이 들어갔는지 확인하고, 같은 자리에 있다면 해당 인덱스는 더 이상 알파벳을 순회하지 않는 식으로 for문을 짜면 될 것같습니다!!
이중 for문을 짜서 , 예를 들어
```java
for(int i = 0 ; i<answer.length; i++){
    for(int j = 0 ; i<submit.length; j++) {
        if(answer[i] == submit[j]) {
            // i++ , 로직
            continue;
    }
}

```
처럼요!

2022-02-23 16:45 UTC, heli-os approved these changes

2022-02-23 16:45 UTC, merged